version: '3.7'

services:
    db:
        image: postgres
        environment:
            - POSTGRES_DB=board
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_INITDB_ARGS=--encoding=UTF-8

    app:
        build:
            context: .
            dockerfile: ./dockerfile
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_NAME=postgres
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
        depends_on:
            - db
        ports:
            - "4000:4000"
        volumes:
            - ./:/app/
